### ISSUE TITLE
Workload gereration for Microsoft Storage and Google Search in Multilate

### ISSUE THREAD

**Issue by kirchhoff** [showanasyabi/peafowl-kvs#1]
Hi, I'm very interested about your work.
Since you have mentioned that you modified Multilate to recreate Facebook ETC, Microsoft Storage and Google Search workloads in the paper, could you provide how to generate them in Multilate?

Thank you very much for your help~!

**Comment by showanasyabi** [comment]
Sorry for the late response. I missed this issue.  We used the following modified Mutilate. If you have any questions, please open an issue there. Thanks 
https://github.com/erfan111/mutilate
